"""Application of migration after programmatic SQL addition of autoincrement=True to Agent model

Revision ID: 3957a1bd48ea
Revises: 52db608125a9
Create Date: 2024-11-06 18:31:40.154949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3957a1bd48ea'
down_revision: Union[str, None] = '52db608125a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
