"""Creation of the EmailManagementModel model

Revision ID: 3cc06ccf5868
Revises: a81d955202e3
Create Date: 2024-08-19 09:53:13.382894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc06ccf5868'
down_revision: Union[str, None] = 'a81d955202e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_management_model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('email_code', sa.String(length=255), nullable=True),
    sa.Column('email_code_time', sa.DateTime(), nullable=True),
    sa.Column('email_link', sa.String(), nullable=True),
    sa.Column('email_link_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Enum('email_verification', 'password_change', 'verified', name='email_management_reason_choice'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_code')
    )
    op.create_index(op.f('ix_email_management_model_id'), 'email_management_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_management_model_id'), table_name='email_management_model')
    op.drop_table('email_management_model')
    # ### end Alembic commands ###
