"""post initial migration

Revision ID: 5313a33a1bfa
Revises: 57fefa726641
Create Date: 2024-10-19 13:31:28.176970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5313a33a1bfa'
down_revision: Union[str, None] = '57fefa726641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_cloud_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_feature_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_feature_id'], ['asset_features.id'], name='fk_asset_cloud_image_asset_feature_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_cloud_image_asset_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_asset_cloud_image_id'), 'asset_cloud_image', ['id'], unique=False)
    op.create_table('asset_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_features_asset_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_features_id'), 'asset_features', ['id'], unique=False)
    op.drop_constraint('fk_agents_user_id', 'agents', type_='foreignkey')
    op.create_foreign_key('fk_assets_cover_image_id', 'assets', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('users', sa.Column('agent_profile_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['agent_profile_id'])
    op.create_foreign_key('fk_user_profile_avatar_id', 'users', 'cloud_image_details', ['profile_avatar_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_users_agent_profile_id', 'users', 'agents', ['agent_profile_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_agent_profile_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_user_profile_avatar_id', 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'agent_profile_id')
    op.drop_constraint('fk_assets_cover_image_id', 'assets', type_='foreignkey')
    op.create_foreign_key('fk_agents_user_id', 'agents', 'users', ['id'], ['id'])
    op.drop_index(op.f('ix_asset_features_id'), table_name='asset_features')
    op.drop_table('asset_features')
    op.drop_index(op.f('ix_asset_cloud_image_id'), table_name='asset_cloud_image')
    op.drop_table('asset_cloud_image')
    # ### end Alembic commands ###
