"""Rename of relations between theAsset, AssetFeature and AssetCloudImage

Revision ID: 5947634d0334
Revises: 201ffaf12eac
Create Date: 2024-10-19 15:29:21.245308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5947634d0334'
down_revision: Union[str, None] = '201ffaf12eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_cloud_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_feature_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_feature_id'], ['asset_features.id'], name='fk_asset_cloud_images_asset_feature_id', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_cloud_images_asset_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_asset_cloud_images_id'), 'asset_cloud_images', ['id'], unique=False)
    op.drop_index('ix_asset_cloud_image_id', table_name='asset_cloud_image')
    op.drop_table('asset_cloud_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_cloud_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secure_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_feature_id'], ['asset_features.id'], name='fk_asset_cloud_image_asset_feature_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_cloud_image_asset_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asset_cloud_image_pkey'),
    sa.UniqueConstraint('public_id', name='asset_cloud_image_public_id_key')
    )
    op.create_index('ix_asset_cloud_image_id', 'asset_cloud_image', ['id'], unique=False)
    op.drop_index(op.f('ix_asset_cloud_images_id'), table_name='asset_cloud_images')
    op.drop_table('asset_cloud_images')
    # ### end Alembic commands ###
