"""Creation of the CloudImageDetail model, and alteration of the User, Asset, and AssetFeature model to suit the CloudImageDetail

Revision ID: d5047b7e59c8
Revises: b3d19f4830b2
Create Date: 2024-09-02 11:11:51.541062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5047b7e59c8'
down_revision: Union[str, None] = 'b3d19f4830b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_image_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('secure_url', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['asset_features.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_cloud_image_details_id'), 'cloud_image_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_image_details_id'), table_name='cloud_image_details')
    op.drop_table('cloud_image_details')
    # ### end Alembic commands ###
