"""creation of AddOn table

Revision ID: 0200b703001e
Revises: 7d5af4d25535
Create Date: 2024-12-28 16:18:28.291144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0200b703001e'
down_revision: Union[str, None] = '7d5af4d25535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_list', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_ons_id'), 'add_ons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_ons_id'), table_name='add_ons')
    op.drop_table('add_ons')
    # ### end Alembic commands ###
