"""Renaming on Asset model from cloud_images to unfeatured_images

Revision ID: 06549a58650f
Revises: 4293a4d3a24f
Create Date: 2025-11-29 09:42:33.536209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06549a58650f'
down_revision: Union[str, None] = '4293a4d3a24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
