"""remodification of user-agent relationship

Revision ID: 0e849ca9c2e7
Revises: 169f6e036a1f
Create Date: 2025-02-01 00:08:59.535583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e849ca9c2e7'
down_revision: Union[str, None] = '169f6e036a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agents_user_id_key', 'agents', type_='unique')
    op.drop_constraint('fk_agents_user_id', 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_agents_user_id', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('agents_user_id_key', 'agents', ['user_id'])
    # ### end Alembic commands ###
