"""Creation of the AggregateRatingAClass and making the Agent model class a subclass of it

Revision ID: 129d8ecc740d
Revises: 13dad9719bb5
Create Date: 2025-05-24 10:16:03.377143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129d8ecc740d'
down_revision: Union[str, None] = '13dad9719bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('total_ratings', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('total_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'total_stars')
    op.drop_column('agents', 'total_ratings')
    # ### end Alembic commands ###
