"""Modification of RoommateFinder and CloudImageDetail model

Revision ID: 13dad9719bb5
Revises: 586986ed4194
Create Date: 2025-05-23 14:45:00.667465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.inspection import inspect


# revision identifiers, used by Alembic.
revision: str = '13dad9719bb5'
down_revision: Union[str, None] = '586986ed4194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    op.add_column('cloud_image_details', sa.Column('roommates_finder_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cloud_image_details_roommates_finder', 'cloud_image_details', 'roommates_finder', ['roommates_finder_id'], ['id'], ondelete='CASCADE')
    
    columns = [col['name'] for col in inspector.get_columns('roomies_application')]
    if 'status' not in columns:
        op.add_column('roomies_application', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='roomies_application_status_choice'), nullable=False))
    
    op.drop_constraint('fk_roommates_finder_cloud_image_details', 'roommates_finder', type_='foreignkey')
    op.create_foreign_key('fk_roommates_finder_users', 'roommates_finder', 'users', ['requester_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_column('roommates_finder', 'room_images_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roommates_finder', sa.Column('room_images_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_roommates_finder_users', 'roommates_finder', type_='foreignkey')
    op.create_foreign_key('fk_roommates_finder_cloud_image_details', 'roommates_finder', 'cloud_image_details', ['room_images_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('roomies_application', 'status')
    op.drop_constraint('fk_cloud_image_details_roommates_finder', 'cloud_image_details', type_='foreignkey')
    op.drop_column('cloud_image_details', 'roommates_finder_id')
    # ### end Alembic commands ###
