"""Modify agent-user relationship

Revision ID: 169f6e036a1f
Revises: ae83b3e6b657
Create Date: 2025-01-31 23:58:04.826032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169f6e036a1f'
down_revision: Union[str, None] = 'ae83b3e6b657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'agents', ['user_id'])
    op.create_foreign_key('fk_agents_user_id', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_agents_user_id', 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
