"""Change of the back_populates property of the asset relationship field from 'featues' to 'asset_features'

Revision ID: 201ffaf12eac
Revises: 5313a33a1bfa
Create Date: 2024-10-19 13:52:49.820390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201ffaf12eac'
down_revision: Union[str, None] = '5313a33a1bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_asset_cloud_image_asset_feature_id', 'asset_cloud_image', 'asset_features', ['asset_feature_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_asset_cloud_image_asset_id', 'asset_cloud_image', 'assets', ['asset_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_asset_features_asset_id', 'asset_features', 'assets', ['asset_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_asset_features_asset_id', 'asset_features', type_='foreignkey')
    op.drop_constraint('fk_asset_cloud_image_asset_id', 'asset_cloud_image', type_='foreignkey')
    op.drop_constraint('fk_asset_cloud_image_asset_feature_id', 'asset_cloud_image', type_='foreignkey')
    # ### end Alembic commands ###
