"""removing id column from AbstractCloudImage model and assigning to CloudImageDetail

Revision ID: 239a5a7d8907
Revises: b9f5158bf7ac
Create Date: 2025-08-07 07:42:22.833008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239a5a7d8907'
down_revision: Union[str, None] = 'b9f5158bf7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
