"""change of assets's category field to Sting for a temporal fix

Revision ID: 23ab00bb47af
Revises: e0404e8dccd8
Create Date: 2024-10-23 18:27:00.038061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ab00bb47af'
down_revision: Union[str, None] = 'e0404e8dccd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'category',
               existing_type=postgresql.ENUM('house', 'hotel', 'land', 'estate', 'fabricated_homes', 'peng_house', 'office_complex', 'oriental_suite', name='asset_category_choice'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'category',
               existing_type=sa.String(),
               type_=postgresql.ENUM('house', 'hotel', 'land', 'estate', 'fabricated_homes', 'peng_house', 'office_complex', 'oriental_suite', name='asset_category_choice'),
               nullable=True)
    # ### end Alembic commands ###
