"""addition of verified, datetime_declined, and datetime_verified to assets table

Revision ID: 24c442ac5459
Revises: 6170fd1f74f8
Create Date: 2025-11-08 16:12:45.519860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c442ac5459'
down_revision: Union[str, None] = '6170fd1f74f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('assets', sa.Column('datetime_declined', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('datetime_verified', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'server_timestamp_ms',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('messages', 'updated_timestamp_ms',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'updated_timestamp_ms',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('messages', 'server_timestamp_ms',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('assets', 'datetime_verified')
    op.drop_column('assets', 'datetime_declined')
    op.drop_column('assets', 'verified')
    # ### end Alembic commands ###
