"""Addition of dial_code to UserSetting model

Revision ID: 363d90f3fdd5
Revises: a684f2551697
Create Date: 2025-07-15 12:30:35.201187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363d90f3fdd5'
down_revision: Union[str, None] = 'a684f2551697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('dial_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'dial_code')
    # ### end Alembic commands ###
