"""creation of relationship 'occupant' from the Area -> UserSetting model; vice versa

Revision ID: 37d7bed12a04
Revises: 91ef2b901918
Create Date: 2025-07-08 05:10:09.343983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d7bed12a04'
down_revision: Union[str, None] = '91ef2b901918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_settings_areas', 'user_settings', 'areas', ['area_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_settings', 'country')
    op.drop_column('user_settings', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_user_settings_areas', 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'area_id')
    # ### end Alembic commands ###
