"""de-nullification of agent_id on property

Revision ID: 4293a4d3a24f
Revises: 96e93b5caac4
Create Date: 2025-11-26 13:53:36.949435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4293a4d3a24f'
down_revision: Union[str, None] = '96e93b5caac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Fetch admin user (assuming at least one exists)
    admin_id = conn.execute(
        sa.text("SELECT id FROM users WHERE is_admin = TRUE LIMIT 1")
    ).scalar()

    if admin_id is None:
        raise RuntimeError(
            "❌ Migration failed: No admin user found. At least one user with is_admin=True must exist."
        )

    #===================
    # Manual Edit
    #===================
    # Assign missing asset.agent_id values
    conn.execute(
        sa.text("""
            UPDATE assets
            SET agent_id = :admin_id
            WHERE agent_id IS NULL
        """),
        {"admin_id": admin_id}
    )

    #===================
    # Auto generation
    #===================
    # Now enforce NOT NULL constraint
    op.alter_column(
        "assets",
        "agent_id",
        existing_type=sa.INTEGER(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
