"""de-nullification of agent_id on property

Revision ID: 4293a4d3a24f
Revises: 96e93b5caac4
Create Date: 2025-11-26 13:53:36.949435

"""
import os
from alembic import op
import sqlalchemy as sa
from dotenv import load_dotenv
from typing import Sequence, Union
from passlib.context import CryptContext


# Explicitly load your custom env file first
load_dotenv(".env.backend")


# revision identifiers, used by Alembic.
revision: str = '4293a4d3a24f'
down_revision: Union[str, None] = '96e93b5caac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ADMIN_EMAIL=os.getenv("ADMIN_EMAIL")
ADMIN_USERNAME=os.getenv("ADMIN_USERNAME")
ADMIN_PASSWORD=os.getenv("ADMIN_PASSWORD")


# === Same hashing logic as your main app ===
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

def upgrade() -> None:
    conn = op.get_bind()

    # 1. Check for existing admin
    admin_id = conn.execute(
        sa.text("SELECT id FROM users WHERE is_admin = TRUE LIMIT 1")
    ).scalar()

    # 2. Create admin if missing
    if admin_id is None:
        if not (ADMIN_EMAIL and ADMIN_USERNAME and ADMIN_PASSWORD):
            raise RuntimeError(
                "❌ ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD must be set in .env.backend"
            )

        hashed_pw = get_password_hash(ADMIN_PASSWORD)

        result = conn.execute(
            sa.text("""
                INSERT INTO users (email, username, password_hash, is_admin, user_role)
                VALUES (:email, :username, :password_hash, TRUE, 'admin')
                RETURNING id
            """),
            {
                "email": ADMIN_EMAIL,
                "username": ADMIN_USERNAME,
                "password_hash": hashed_pw,
            }
        )

        admin_id = result.scalar()
        print(f"✅ No admin found — created admin with id={admin_id}")

    # 3. Assign missing agent_id fields to this admin
    conn.execute(
        sa.text("""
            UPDATE assets
            SET agent_id = :admin_id
            WHERE agent_id IS NULL
        """),
        {"admin_id": admin_id}
    )

    # 4. Enforce NOT NULL
    op.alter_column(
        "assets",
        "agent_id",
        existing_type=sa.INTEGER(),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
