"""Modification of Message model, addition of sent_messages, received_messages to the User model, modification of thread_chat_session_association, modification of thread_participants_association

Revision ID: 440ab6100f42
Revises: 0200b703001e
Create Date: 2025-01-06 17:36:55.827628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440ab6100f42'
down_revision: Union[str, None] = '0200b703001e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chat_sessions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('updated_timestamp', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='fk_messages_recipient_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_messages_sender_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='fk_messages_thread_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('thread_participants_association',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['users.id'], name='fk_thread_participants_association_thread_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['threads.id'], name='fk_thread_participants_association_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_table('thread_chat_session_association',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name='fk_thread_chat_session_association_chat_session_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='fk_thread_chat_session_association_thread_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('thread_id', 'chat_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_chat_session_association')
    op.drop_table('thread_participants_association')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
