"""modification of asset_id on AbstractCloudImage to cloud_asset_id

Revision ID: 46bc2e062333
Revises: dad4a73567aa
Create Date: 2024-10-22 14:20:11.664390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bc2e062333'
down_revision: Union[str, None] = 'dad4a73567aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_image_details', sa.Column('asset_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_image_details', 'asset_id')
    # ### end Alembic commands ###
