"""Creation of GoogleOAuthDetail model, and modification of User model to include the google_oauth_detail field

Revision ID: 497e148145cf
Revises: abed31a9ec91
Create Date: 2025-03-17 17:27:38.295217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497e148145cf'
down_revision: Union[str, None] = 'abed31a9ec91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_google_oauth_details_users', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_details_id'), 'google_oauth_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_oauth_details_id'), table_name='google_oauth_details')
    op.drop_table('google_oauth_details')
    # ### end Alembic commands ###
