"""addition of lease duration to the Asset model

Revision ID: 52db608125a9
Revises: 23ab00bb47af
Create Date: 2024-11-01 07:56:25.921065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52db608125a9'
down_revision: Union[str, None] = '23ab00bb47af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('lease_duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'lease_duration')
    # ### end Alembic commands ###
