"""Addition of category field to Roommate finder model

Revision ID: 592ada0e7370
Revises: d65ff6f3f8c5
Create Date: 2025-06-26 08:38:43.917347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592ada0e7370'
down_revision: Union[str, None] = 'd65ff6f3f8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'availability',
               existing_type=sa.TEXT(),
               type_=sa.Enum('available', 'unavailable', 'reserved', 'pending', 'sold', 'rented', 'maintenance', name='asset_availability_status'),
               existing_nullable=False)
    op.drop_column('assets', 'has_features')
    op.add_column('messages', sa.Column('media_urls', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('additional_metadata', sa.String(), nullable=True))
    op.add_column('roommates_finder', sa.Column('category', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'custom', name='client_gender_choice'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('roommates_finder', 'category')
    op.drop_column('messages', 'additional_metadata')
    op.drop_column('messages', 'media_urls')
    op.add_column('assets', sa.Column('has_features', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('assets', 'availability',
               existing_type=sa.Enum('available', 'unavailable', 'reserved', 'pending', 'sold', 'rented', 'maintenance', name='asset_availability_status'),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
