"""Addition of category field to Roommate finder model,
Addition of media_urls field to messages
Addition of additional_metadata field to messages
Addition of category field to roommates_finder
Addition of category field to roommates_finder

Revision ID: 592ada0e7370
Revises: d65ff6f3f8c5
Create Date: 2025-06-26 08:38:43.917347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592ada0e7370'
down_revision: Union[str, None] = 'd65ff6f3f8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'has_features')
    op.add_column('messages', sa.Column('media_urls', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('additional_metadata', sa.String(), nullable=True))
    op.add_column('roommates_finder', sa.Column('category', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roommates_finder', 'category')
    op.drop_column('messages', 'additional_metadata')
    op.drop_column('messages', 'media_urls')
    op.add_column('assets', sa.Column('has_features', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
