"""Creation of RoomieApplication and RoommateFinder models

Revision ID: 5fa57edb59b4
Revises: a3e4431b8015
Create Date: 2025-05-22 18:31:23.955166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa57edb59b4'
down_revision: Union[str, None] = 'a3e4431b8015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roommate_finders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_roomies', sa.Integer(), nullable=False),
    sa.Column('extra_conditions', sa.Text(), nullable=True),
    sa.Column('room_images_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(extra_conditions) <= 500', name='check_max_condition_length'),
    sa.CheckConstraint('max_roomies <= 10', name='check_max_roomies'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_roommate_finders_area', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_roommate_finders_users', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['room_images_id'], ['cloud_image_details.id'], name='fk_roommate_finders_cloud_image_details', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roommate_finders_id'), 'roommate_finders', ['id'], unique=False)
    op.create_table('roomies_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datetime_approved_or_rejected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='roomies_application_status_choice'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roommate_finder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roommate_finder_id'], ['roommate_finders.id'], name='fk_roommate_applications', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_roomies_application_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomies_application_id'), 'roomies_application', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roomies_application_id'), table_name='roomies_application')
    op.drop_table('roomies_application')
    op.drop_index(op.f('ix_roommate_finders_id'), table_name='roommate_finders')
    op.drop_table('roommate_finders')
    # ### end Alembic commands ###
