"""removal of created at, and inclusion of timestamp field to 'notifications' table

Revision ID: 6170fd1f74f8
Revises: 2bf8d13ee9a5
Create Date: 2025-10-06 01:18:48.094056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6170fd1f74f8'
down_revision: Union[str, None] = '2bf8d13ee9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('timestamp', sa.Float(), nullable=False))
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'timestamp')
    # ### end Alembic commands ###
