"""Inclusion of asset interaction attributes

Revision ID: 6ca0be9f8527
Revises: d8911d227c23
Create Date: 2026-03-16 16:37:21.151513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from property_street_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused

# revision identifiers, used by Alembic.
revision: str = '6ca0be9f8527'
down_revision: Union[str, None] = 'd8911d227c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


intent_factor_values = ['like', 'save', 'share', 'cart', 'click', 'contact', 'view', 'search_result_appearance']
intent_factor = ENUM(*intent_factor_values, name='intent_factor', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('intent_factor', intent_factor_values)
    op.create_table('property_interaction_event',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factor', intent_factor, nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['assets.id'], name='fk_property_interaction_event_asset_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_intent_events_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_interaction_event_factor'), 'property_interaction_event', ['factor'], unique=False)
    op.create_index(op.f('ix_property_interaction_event_id'), 'property_interaction_event', ['id'], unique=False)
    op.create_index(op.f('ix_property_interaction_event_property_id'), 'property_interaction_event', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_interaction_event_user_id'), 'property_interaction_event', ['user_id'], unique=False)
    op.create_table('user_stats_per_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('cart', sa.Boolean(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_stats_asset_id_assets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_stats_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_per_property_id'), 'user_stats_per_property', ['id'], unique=False)
    op.add_column('assets', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('shares', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('contacts', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('carts', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('total_ratings', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('total_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'total_stars')
    op.drop_column('assets', 'total_ratings')
    op.drop_column('assets', 'carts')
    op.drop_column('assets', 'contacts')
    op.drop_column('assets', 'clicks')
    op.drop_column('assets', 'views')
    op.drop_column('assets', 'shares')
    op.drop_column('assets', 'saves')
    op.drop_column('assets', 'likes')
    op.drop_index(op.f('ix_user_stats_per_property_id'), table_name='user_stats_per_property')
    op.drop_table('user_stats_per_property')
    op.drop_index(op.f('ix_property_interaction_event_user_id'), table_name='property_interaction_event')
    op.drop_index(op.f('ix_property_interaction_event_property_id'), table_name='property_interaction_event')
    op.drop_index(op.f('ix_property_interaction_event_id'), table_name='property_interaction_event')
    op.drop_index(op.f('ix_property_interaction_event_factor'), table_name='property_interaction_event')
    op.drop_table('property_interaction_event')
    drop_enum_if_unused('intent_factor')
    # ### end Alembic commands ###
