"""Rename of created_at field in EventBase Abs model to timestamp_ms

Revision ID: 6cef8427174c
Revises: 6ca0be9f8527
Create Date: 2026-04-01 22:46:17.835635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cef8427174c'
down_revision: Union[str, None] = '6ca0be9f8527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_interaction_event', sa.Column('timestamp_ms', sa.BigInteger(), nullable=True))
    op.drop_column('property_interaction_event', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_interaction_event', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('property_interaction_event', 'timestamp_ms')
    # ### end Alembic commands ###
