"""Creation of Area model and addition of the area field to assets and asset_requests table

Revision ID: 7865e576688d
Revises: dd9e23f0c285
Create Date: 2025-04-15 09:52:28.659311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7865e576688d'
down_revision: Union[str, None] = 'dd9e23f0c285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state_or_province', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('city_or_town', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('building_name_or_suite', sa.String(), nullable=False),
    sa.Column('zip_or_postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.add_column('assets', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_assets_areas', 'assets', 'areas', ['area_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_column('assets', 'address')
    op.drop_column('assets', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_assets_areas', 'assets', type_='foreignkey')
    op.drop_column('assets', 'area_id')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
