"""modification of availability field of asset model

Revision ID: 7d5af4d25535
Revises: 52db608125a9
Create Date: 2024-12-21 23:44:06.868873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5af4d25535'
down_revision: Union[str, None] = '52db608125a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'availability',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'availability',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
