"""Modification of the Notification model

Revision ID: 80654c023515
Revises: 239a5a7d8907
Create Date: 2025-09-12 18:39:20.458552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80654c023515'
down_revision: Union[str, None] = '239a5a7d8907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

notification_type_enum = postgresql.ENUM(
    'chat', 'roommate_finder', 'asset_request', 'property', 'generic', 
    name='notification_type_choice'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type before using it
    notification_type_enum.create(op.get_bind())

    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('fmt_not', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column(
        'notifications', 
        'n_type',
        existing_type=sa.VARCHAR(),
        type_=notification_type_enum,
        postgresql_using="n_type::notification_type_choice",
        existing_nullable=False
    )
    op.drop_column('notifications', 'n_serialized_obj')
    op.drop_column('notifications', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('n_serialized_obj', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'n_type',
               existing_type=sa.Enum('chat', 'roommate_finder', 'asset_request', 'property', 'generic', name='notification_type_choice'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notifications', 'fmt_not')
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
