"""conversion of Message fmt_msg from String to JSONB

Revision ID: 81d45c138470
Revises: c63f1835a0a7
Create Date: 2025-07-23 04:24:40.119651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d45c138470'
down_revision: Union[str, None] = 'c63f1835a0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE messages
        ALTER COLUMN fmt_msg
        TYPE JSONB
        USING fmt_msg::jsonb
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE messages
        ALTER COLUMN fmt_msg
        TYPE VARCHAR
        USING fmt_msg::text
        """)
    # ### end Alembic commands ###
