"""addition of rating relationship to user

Revision ID: 91ef2b901918
Revises: 8403a682d5ea
Create Date: 2025-07-05 20:48:06.268492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ef2b901918'
down_revision: Union[str, None] = '8403a682d5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_ratings', 'users', 'ratings', ['rating_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_ratings', 'users', type_='foreignkey')
    op.drop_column('users', 'rating_id')
    # ### end Alembic commands ###
