"""Cascade deletion of cover_image on asset deletion

Revision ID: 96e93b5caac4
Revises: 24c442ac5459
Create Date: 2025-11-26 08:29:06.229646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e93b5caac4'
down_revision: Union[str, None] = '24c442ac5459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #======================
    # Maual edit
    #======================
    op.execute("""
        UPDATE assets
        SET verified = FALSE
        WHERE verified IS NULL
    """)
    
    #======================
    # Automated generation
    #======================
    op.alter_column('assets', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('fk_assets_cover_image_id'), 'assets', type_='foreignkey')
    op.create_foreign_key('fk_assets_cover_image_id', 'assets', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assets_cover_image_id', 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_assets_cover_image_id'), 'assets', 'cloud_image_details', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.alter_column('assets', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
