"""modifiction of threads-participants relationship table

Revision ID: 9a34da851371
Revises: 440ab6100f42
Create Date: 2025-01-18 06:27:13.660268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a34da851371'
down_revision: Union[str, None] = '440ab6100f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_participants_association',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name='fk_threads_participants_association_thread_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_threads_participants_association_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.drop_table('thread_participants_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_participants_association',
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['users.id'], name='fk_thread_participants_association_thread_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['threads.id'], name='fk_thread_participants_association_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('thread_id', 'user_id', name='thread_participants_association_pkey')
    )
    op.drop_table('threads_participants_association')
    # ### end Alembic commands ###
