"""Modification of Area model nullable fields

Revision ID: a3e4431b8015
Revises: d825878a30dd
Create Date: 2025-05-21 10:25:07.490328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e4431b8015'
down_revision: Union[str, None] = 'd825878a30dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'building_name_or_suite',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'building_name_or_suite',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
