"""addition of fmt_msg_txt to the Message model

Revision ID: a684f2551697
Revises: 37d7bed12a04
Create Date: 2025-07-13 06:40:57.304624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684f2551697'
down_revision: Union[str, None] = '37d7bed12a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('fmt_msg_txt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'fmt_msg_txt')
    # ### end Alembic commands ###
