"""reflection of User model cover_image to profile_avatar

Revision ID: abed31a9ec91
Revises: d6edfb68854b
Create Date: 2025-03-15 10:56:30.689723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abed31a9ec91'
down_revision: Union[str, None] = 'd6edfb68854b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
