"""change of relationship class argument on User's threads attribute from  Threads to Thread

Revision ID: ae83b3e6b657
Revises: 9a34da851371
Create Date: 2025-01-18 07:00:31.777132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae83b3e6b657'
down_revision: Union[str, None] = '9a34da851371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
