"""Creation of notifications, ratings, asset_requests, request_agent_association and request_asset_association table

Revision ID: bae45f807597
Revises: 7865e576688d
Create Date: 2025-04-27 11:39:01.438120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae45f807597'
down_revision: Union[str, None] = '7865e576688d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('n_type', sa.String(), nullable=True),
    sa.Column('n_serialized_obj', sa.String(), nullable=True),
    sa.Column('n_status', sa.Enum('read', 'delivered', 'undelivered', name='notification_state_choice'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_users', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('score <= 5', name='check_score_max'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='fk_ratings_agents', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_ratings_areas', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_table('asset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_asset_requests_areas', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='fk_asset_requests_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_requests_id'), 'asset_requests', ['id'], unique=False)
    op.create_table('request_agent_association',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='fk_request_agent_association_agents', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['asset_requests.id'], name='fk_request_agent_association_asset_requests', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'agent_id')
    )
    op.create_table('request_asset_association',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_request_agent_association_assets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['asset_requests.id'], name='fk_request_agent_association_asset_requests', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_asset_association')
    op.drop_table('request_agent_association')
    op.drop_index(op.f('ix_asset_requests_id'), table_name='asset_requests')
    op.drop_table('asset_requests')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
