"""Making the Area class model a subclass of the AggregateRatingAClass

Revision ID: d65ff6f3f8c5
Revises: 129d8ecc740d
Create Date: 2025-05-24 10:17:56.657784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65ff6f3f8c5'
down_revision: Union[str, None] = '129d8ecc740d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('total_ratings', sa.Integer(), nullable=True))
    op.add_column('areas', sa.Column('total_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'total_stars')
    op.drop_column('areas', 'total_ratings')
    # ### end Alembic commands ###
