"""modification of Message fields; timestamp->server_timestamp_ms, updated_timestamp->updated_timestamp_ms

Revision ID: d6afb4927ce1
Revises: 40de413421e4
Create Date: 2025-07-20 01:57:31.786642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6afb4927ce1'
down_revision: Union[str, None] = '40de413421e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('server_timestamp_ms', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('updated_timestamp_ms', sa.Integer(), nullable=True))
    op.drop_column('messages', 'updated_timestamp')
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('updated_timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'updated_timestamp_ms')
    op.drop_column('messages', 'server_timestamp_ms')
    # ### end Alembic commands ###
