"""Modification of UserSetting field to allow nullability

Revision ID: d6edfb68854b
Revises: cc6a80ba2d97
Create Date: 2025-03-07 22:48:32.463327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6edfb68854b'
down_revision: Union[str, None] = 'cc6a80ba2d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_user_settings_users', 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_settings_users', 'user_settings', type_='foreignkey')
    # ### end Alembic commands ###
