"""creation of foreign key constrainsts notification_users, ratings_areas, ratings_agents

Revision ID: d825878a30dd
Revises: bae45f807597
Create Date: 2025-04-27 16:22:28.581019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd825878a30dd'
down_revision: Union[str, None] = 'bae45f807597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_notifications_users', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_ratings_areas', 'ratings', 'areas', ['area_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_ratings_agents', 'ratings', 'agents', ['agent_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ratings_agents', 'ratings', type_='foreignkey')
    op.drop_constraint('fk_ratings_areas', 'ratings', type_='foreignkey')
    op.drop_constraint('fk_notifications_users', 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
