"""Addition of singleton model

Revision ID: d8911d227c23
Revises: e57bade0885a
Create Date: 2026-01-26 10:19:37.930271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8911d227c23'
down_revision: Union[str, None] = 'e57bade0885a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singleton',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(
        "ALTER TABLE singleton "
        "ADD CONSTRAINT singleton_id_check CHECK (id = 1)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE singleton "
        "DROP CONSTRAINT singleton_id_check"
    )
    op.drop_table('singleton')
    # ### end Alembic commands ###
