"""
1. addition of created_at and updated_at field to AbstractCloudImage 
2. conversion of Asset's category field from string to enum

Revision ID: dad4a73567aa
Revises: 5947634d0334
Create Date: 2024-10-21 10:31:23.494614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'dad4a73567aa'
down_revision: Union[str, None] = '5947634d0334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define the new Enum type for asset categories
asset_category_enum = sa.Enum(
    'house', 'hotel', 'land', 'estate', 'fabricated_homes', 
    'peng_house', 'office_complex', 'oriental_suite', 
    name='asset_category_choice'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum type before altering the category column
    asset_category_enum.create(op.get_bind())  # This explicitly creates the Enum type in the DB
    
    # Add updated_at column to asset_cloud_images table
    op.add_column('asset_cloud_images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Alter created_at column to use TIMESTAMPTZ with explicit casting
    op.alter_column('asset_cloud_images', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               postgresql_using="created_at::timestamp with time zone")  # Explicit cast

    # Add foreign keys
    op.create_foreign_key('fk_asset_cloud_images_asset_feature_id', 'asset_cloud_images', 'asset_features', ['asset_feature_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_asset_cloud_images_asset_id', 'asset_cloud_images', 'assets', ['asset_id'], ['id'], ondelete='CASCADE', use_alter=True)

    # Alter the category column to use the new Enum type
    op.alter_column('assets', 'category',
               existing_type=sa.VARCHAR(),
               type_=asset_category_enum,
               nullable=True,
               postgresql_using="category::asset_category_choice"
               )

    # Add updated_at column to cloud_image_details table
    op.add_column('cloud_image_details', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Alter created_at column to use TIMESTAMPTZ with explicit casting
    op.alter_column('cloud_image_details', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               postgresql_using="created_at::timestamp with time zone")  # Explicit cast
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert the category column back to VARCHAR
    op.alter_column('assets', 'category',
               existing_type=asset_category_enum,
               type_=sa.VARCHAR(),
               nullable=False)

    # Drop the Enum type (needs to happen after the column is reverted)
    asset_category_enum.drop(op.get_bind())

    # Drop updated_at column from cloud_image_details
    op.drop_column('cloud_image_details', 'updated_at')

    # Revert created_at column in cloud_image_details to VARCHAR
    op.alter_column('cloud_image_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=False)

    # Drop foreign keys and revert created_at for asset_cloud_images
    op.drop_constraint('fk_asset_cloud_images_asset_id', 'asset_cloud_images', type_='foreignkey')
    op.drop_constraint('fk_asset_cloud_images_asset_feature_id', 'asset_cloud_images', type_='foreignkey')

    op.alter_column('asset_cloud_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=False)

    op.drop_column('asset_cloud_images', 'updated_at')
    # ### end Alembic commands ###
