"""modifiation of field 'date_applied' to 'created_at' on the 'roomies_application' table

Revision ID: dce86deeb27c
Revises: ff2a7ccc2c28
Create Date: 2025-09-18 12:41:35.541612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce86deeb27c'
down_revision: Union[str, None] = 'ff2a7ccc2c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roomies_application', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('roomies_application', 'date_applied')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roomies_application', sa.Column('date_applied', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('roomies_application', 'created_at')
    # ### end Alembic commands ###
