"""creation of CartItem

Revision ID: dd9e23f0c285
Revises: 497e148145cf
Create Date: 2025-03-28 19:34:01.536530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9e23f0c285'
down_revision: Union[str, None] = '497e148145cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity <= 1', name='check_quantity_max'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_cart_items_assets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_cart_items_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.add_column('assets', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('assets', 'amount')
    op.create_foreign_key('fk_google_oauth_details_users', 'google_oauth_details', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_google_oauth_details_users', 'google_oauth_details', type_='foreignkey')
    op.add_column('assets', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('assets', 'price')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
