"""modification of asset_tag_association table

Revision ID: e0404e8dccd8
Revises: 46bc2e062333
Create Date: 2024-10-22 17:26:33.146727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0404e8dccd8'
down_revision: Union[str, None] = '46bc2e062333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_cloud_images', sa.Column('cloud_asset_id', sa.String(), nullable=False))
    op.drop_constraint('asset_tag_association_tag_id_fkey', 'asset_tag_association', type_='foreignkey')
    op.drop_constraint('asset_tag_association_asset_id_fkey', 'asset_tag_association', type_='foreignkey')
    op.create_foreign_key('fk_asset_tag_association_tag_id', 'asset_tag_association', 'tags', ['tag_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_asset_tag_association_asset_id', 'asset_tag_association', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.add_column('cloud_image_details', sa.Column('cloud_asset_id', sa.String(), nullable=False))
    op.drop_column('cloud_image_details', 'asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_image_details', sa.Column('asset_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cloud_image_details', 'cloud_asset_id')
    op.drop_constraint('fk_asset_tag_association_asset_id', 'asset_tag_association', type_='foreignkey')
    op.drop_constraint('fk_asset_tag_association_tag_id', 'asset_tag_association', type_='foreignkey')
    op.create_foreign_key('asset_tag_association_asset_id_fkey', 'asset_tag_association', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key('asset_tag_association_tag_id_fkey', 'asset_tag_association', 'tags', ['tag_id'], ['id'])
    op.drop_column('asset_cloud_images', 'cloud_asset_id')
    # ### end Alembic commands ###
