"""removal of roomies_application_roomies_applicants_association, and modification of roomies_application to enforce unique constraint of one applicant per roommate request

Revision ID: e2e2e0d8f9d2
Revises: 80654c023515
Create Date: 2025-09-18 10:59:49.440397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e2e0d8f9d2'
down_revision: Union[str, None] = '80654c023515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomies_application_roomies_applicants_association')
    op.alter_column('notifications', 'n_type',
               existing_type=postgresql.ENUM('chat', 'roommate_finder', 'asset_request', 'property', 'generic', name='notification_type_choice'),
               nullable=False)
    op.add_column('roomies_application', sa.Column('applicant_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_applicant_per_finder', 'roomies_application', ['roommate_finder_id', 'applicant_id'])
    op.create_foreign_key('fk_roomies_application', 'roomies_application', 'users', ['applicant_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_roomies_application', 'roomies_application', type_='foreignkey')
    op.drop_constraint('uq_applicant_per_finder', 'roomies_application', type_='unique')
    op.drop_column('roomies_application', 'applicant_id')
    op.alter_column('notifications', 'n_type',
               existing_type=postgresql.ENUM('chat', 'roommate_finder', 'asset_request', 'property', 'generic', name='notification_type_choice'),
               nullable=True)
    op.create_table('roomies_application_roomies_applicants_association',
    sa.Column('roomies_application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roomies_application_id'], ['roomies_application.id'], name=op.f('fk_roomies_application_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_roomies_application'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roomies_application_id', 'user_id', name=op.f('roomies_application_roomies_applicants_association_pkey'))
    )
    # ### end Alembic commands ###
