"""Addition of listing_type field to Asset model and migration of Asset status -> listing type, and status -> 'available'

Revision ID: e57bade0885a
Revises: e84ca2d4187c
Create Date: 2026-01-17 13:35:26.417191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from property_street_backend.alembic.utils import create_enum_if_not_exists, drop_enum_if_unused

# revision identifiers, used by Alembic.
revision: str = 'e57bade0885a'
down_revision: Union[str, None] = 'e84ca2d4187c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

availablity_status_values = ['available', 'unavailable', 'reserved', 'pending', 'sold', 'rented', 'maintenance']
asset_availability_status = ENUM(*availablity_status_values, name='asset_availability_status', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new column (nullable temporarily to allow data copy)
    op.add_column(
        "assets",sa.Column("listing_type", sa.String(), nullable=True)
    ) 
    # 2. Copy status → listing_type
    op.execute("""
        UPDATE assets
        SET listing_type = status::text
    """)
    # 2. Copy available → status
    op.execute("""
        UPDATE assets
        SET status = 'available'
    """)
    op.alter_column(
        "assets", "listing_type", nullable=False
    )
    op.drop_column('assets', 'availability')
    drop_enum_if_unused('asset_availability_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_enum_if_not_exists('asset_availability_status', availablity_status_values)
    # 1. Restore availability column
    op.add_column('assets', sa.Column('availability', asset_availability_status, server_default="available", nullable=False))
    # 2. Restore status values from listing_type
    op.execute("""
        UPDATE assets
        SET status = listing_type::text
    """)
    op.drop_column('assets', 'listing_type')
    # ### end Alembic commands ###
