"""modification of message field in Message model to fmt_msg

Revision ID: e73688d0d0e8
Revises: 363d90f3fdd5
Create Date: 2025-07-18 18:16:38.600912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73688d0d0e8'
down_revision: Union[str, None] = '363d90f3fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('fmt_msg', sa.String(), nullable=True))
    op.drop_column('messages', 'additional_metadata')
    op.drop_column('messages', 'media_urls')
    op.drop_column('messages', 'fmt_msg_txt')
    op.drop_column('messages', 'text_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('fmt_msg_txt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('media_urls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('additional_metadata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'fmt_msg')
    # ### end Alembic commands ###
