"""addition of 'created_at'

Revision ID: f76ff74665a1
Revises: 06549a58650f
Create Date: 2025-12-16 16:16:32.021491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76ff74665a1'
down_revision: Union[str, None] = '06549a58650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roommates_finder', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roommates_finder', 'created_at')
    # ### end Alembic commands ###
