"""addition of cached_roomies_application_ids to users table

Revision ID: ff2a7ccc2c28
Revises: e2e2e0d8f9d2
Create Date: 2025-09-18 11:46:39.009976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff2a7ccc2c28'
down_revision: Union[str, None] = 'e2e2e0d8f9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cached_roomies_application_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cached_roomies_application_ids')
    # ### end Alembic commands ###
