from pathlib import Path
from decouple import config


ENVIRONMENT = config("ENVIRONMENT")

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Debug mode
DEBUG = True if ENVIRONMENT == 'development' else False

# Allowed hosts for the application
ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

# SQLAlchemy database configuration for PostgreSQL
DATABASE_URL = config('DATABASE_URL')

TEST_DATABASE_URL = config('TEST_DATABASE_URL')

# REDIS settings
REDIS_HOST = config('TEST_REDIS_HOST') if DEBUG else config('REDIS_HOST')
TEST_REDIS_CACHE_DB = int(config('TEST_REDIS_CACHE_DB'))
PROD_REDIS_CACHE_DB = int(config('PROD_REDIS_CACHE_DB'))
REDIS_CACHE_DB = TEST_REDIS_CACHE_DB if DEBUG else PROD_REDIS_CACHE_DB
NEWLY_CREATED_ASSET_TTL = int(config('NEWLY_CREATED_ASSET_TTL'))
TEST_NEWLY_CREATED_ASSET_TTL = int(config('TEST_NEWLY_CREATED_ASSET_TTL'))
SEARCH_UNIT_TTL = int(config('SEARCH_UNIT_TTL'))

TEST_CART_OFFLOAD_SCHEDULE =  int(config('TEST_CART_OFFLOAD_SCHEDULE')) 
PROD_CART_OFFLOAD_SCHEDULE = int(config('PROD_CART_OFFLOAD_SCHEDULE'))
CART_OFFLOAD_SCHEDULE = TEST_CART_OFFLOAD_SCHEDULE if DEBUG else PROD_CART_OFFLOAD_SCHEDULE

TEST_CART_TTL = int(config('TEST_CART_TTL'))
PROD_CART_TTL = int(config('PROD_CART_TTL'))

CHAT_LAZY_OFFLOAD_SCHEDULE = int(config('CHAT_LAZY_OFFLOAD_SCHEDULE'))
TEST_CHAT_LAZY_OFFLOAD_SCHEDULE = int(config('TEST_CHAT_LAZY_OFFLOAD_SCHEDULE'))

CHAT_TTL = int(config('CHAT_TTL'))
TEST_CHAT_TTL = int(config('TEST_CHAT_TTL'))

AGENT_NOTIFICATION_ENTRY_OFFLOAD_SCHEDULE = int(config('AGENT_NOTIFICATION_ENTRY_OFFLOAD_SCHEDULE'))
TEST_AGENT_NOTIFICATION_ENTRY_OFFLOAD_SCHEDULE = int(config('TEST_AGENT_NOTIFICATION_ENTRY_OFFLOAD_SCHEDULE'))

# CORS settings
CORS_ORIGINS = config('CORS_ORIGINS').split(',')

# JWT settings
JWT_SECRET_KEY = config('JWT_SECRET_KEY')
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_DELTA = int(config('JWT_EXPIRATION_DELTA'))

# google credentials
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URL = config('TEST_GOOGLE_REDIRECT_URL') if DEBUG else config('PROD_GOOGLE_CLIENT_SECRET')